### ISSUE TITLE
readme详细一些！

### ISSUE THREAD

**Issue by jiangph1001** [fengtongtong/pcap_feature#2]
你的readme写的也太少了，起码说一下怎么使用吧，不能让人挨个去读你的代码猜吧

**Comment by ttfeng42** [comment]
我晚上回去更新一下



---原始邮件---
发件人: "jiangph1001"<notifications@github.com&gt;
发送时间: 2020年4月19日(周日) 中午1:11
收件人: "fengtongtong/pcap_feature"<pcap_feature@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [fengtongtong/pcap_feature] readme详细一些！ (#2)




 
你的readme写的也太少了，起码说一下怎么使用吧，不能让人挨个去读你的代码猜吧
